receivers:
  otlp:
    protocols:
      grpc:
exporters:
  otlp:
    endpoint: jaeger:14250
    tls:
      insecure: true
  logging:
processors:
  batch:
extensions:
  health_check:
  pprof:
service:
  extensions: [pprof, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]
      processors: [batch]